---
functional:
  - Неавторизованный пользователь может сыграть пробную игру – игра простого уровня сложности против бота продолжительностью 30 минут 
  - Пользователь может зарегистрироваться на сайте по электронной почте
  - Пользователь может авторизоваться на сайте через аккаунт GitHub
  - Пользователь может создать игру против бота, друга, другого пользователя
  - При создании игры пользователь может выбрать настройки игры – сложность (простая, легкая, средняя, трудная), продолжительность (от 3 до 60 минут), задание
  - При создании игры пользователь может отфильтровать задания по сложности игры, по названию задания и по тегу задания, а также применить опцию выбора случайного задания игры
  - Пользователь может играть, используя разные языки программирования (JavaScript, TypeScript, Dart, Go, C++, C#, Java, Kotlin, Haskell, Ruby, Elixir, Php, Python, Clojure)
  - Пользователь может досрочно завершить игру (сдаться)
  - Пользователь, побеждая в играх против пользователей (кроме ботов), зарабатывает очки рейтинга, проигрывая или сдаваясь в играх – теряет, по результатам игр против ботов очки рейтинга не начисляются
  - Ранг должен присваиваться пользователям в зависимости от рейтинга. Пользователю с самым высоким рейтингом должен присвоиться 1 ранг. Новые ранги должны присваиваться пользователям с разницей в одно очко рейтинга. Пользователи с одинаковым рейтингом должны иметь один ранг
  - На странице настроек профиля пользователь может изменить – имя, язык программирования, тип звука, уровень громкости звука, а также может привязать другие аккаунты (GitHub, Discord)
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (Google Chrome, Safari, Firefox)
  - Сайт должен быть способен обрабатывать большое количество трафика (100 одновременных пользователей)
implicit:
  - Неавторизованному пользователю присваивается временное имя пользователя "John Doe"
  - После регистрации по электронной почте пользователю генерируется аватар, после авторизации на сайте через аккаунт Github в профиль пользователя автоматически подгружается имя пользователя и аватар из аккаунта Github
  - После регистрации (первой авторизации) на сайте пользователю должен присваиваться начальный рейтинг = 1200
  - Для новых пользователей должно показываться руководство по игре
  - При создании игры должны быть выставлены настройки по умолчанию (сложность – простая, тип – с другим пользователем, продолжительность – 8 минут, задание – случайное, теги – не выбраны)
  - Пользователь должен иметь возможность сменить язык программирования в игре
  - В игре в редакторе кода для каждого языка программирования должен отображаться шаблон кода
  - Игры, окончившиеся по истечению времени, не отображаются и не учитываются в статистике
  - Начисление и снятие очков рейтинга должно зависеть от рейтинга оппонентов и от сложности игры. У ботов начисление и снятие очков рейтинга не осуществляется
  - На странице настроек профиля должны быть выставлены настройки по умолчанию (язык программирования – JavaScript, тип звука – Dendy, уровень громкости звука – 5 (промежутка от 0 до 10))
  - Пользователь может восстановить пароль от аккаунта 
  - Пользователь может выйти из аккаунта
