---
functional:
  - Неавторизованный пользователь может сыграть пробную игру против бота, зарегистрироваться, авторизоваться на сайте
  - Пользователь может зарегистрироваться на сайте по электронной почте
  - Пользователь может авторизоваться на сайте через аккаунт Github
  - Авторизованному пользователю на главной странице должны отображаться - блок игр, блок чата, блок лидеров
  - Сайт должен иметь страницы - настроек профиля, рейтинга пользователей, заданий, турниров
  - У всех пользователей (включая ботов) должна быть страница профиля, на которой отображается - аватар, имя, язык программирования, дата первой авторизации (дата добавления – у ботов), ссылка на аккаунт Github (кроме ботов), достижения, ранг, рейтинг, статистика по результатам завершенных игр
  - Пользователь может создать игру против бота, друга, другого пользователя
  - При создании игры пользователь может выбрать настройки игры - сложность, продолжительность, задание
  - При создании игры пользователь может отфильтровать задания по сложности игры, по названию задания и по тегу задания, а также выбрать опцию генерации случайного задания игры
  - Пользователь может играть, используя разные языки программирования
  - Пользователь может досрочно завершить игру (сдаться)
  - Пользователь, побеждая в играх против пользователей (кроме ботов), зарабатывает очки рейтинга, проигрывая или сдаваясь в играх – теряет, по результатам игр против ботов очки рейтинга не начисляются 
  - Ранг должен присваиваться пользователям в зависимости от рейтинга. Пользователю с самым высоким рейтингом будет присваиваться 1 ранг. Новые ранги будут присваиваться пользователям с разницей в одно очко рейтинга. Пользователи с одинаковым рейтингом будут иметь один ранг
  - Пользователи (кроме ботов) могут зарабатывать достижения играя в игры
  - На странице настроек профиля пользователь может изменить - имя, язык программирования, тип звукового сигнала, уровень громкости звука, а также может привязать другие аккаунты 
  - На странице рейтинга пользователей отображается информация - №, имя, ранг, рейтинг, количество сыгранных игр, дата первой авторизации (дата добавления – у ботов), наличие аккаунта Github
  - На странице рейтинга пользователей можно отсортировать по рангу, рейтингу, количеству сыгранных игр, дате первой авторизации (дате добавления – у ботов), пользователей можно искать по имени
  - На странице заданий отображается информация - название, сложность, теги, источник, состояние, видимость, действия
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (100 одновременных пользователей)
implicit:
  - После регистрации (первой авторизации) на сайте пользователю создается страница профиля
  - После регистрации по электронной почте генерируется аватар, после авторизации на сайте через аккаунт Github в профиль пользователя автоматически подгружается имя пользователя и аватар из аккаунта Github
  - После регистрации (первой авторизации) на сайте пользователю должен присваиваться начальный рейтинг
  - В блоке игр на главной странице должны отображаться текущие и завершенные игры
  - В блоке чата на главной странице должны отображаться онлайн пользователи (кроме ботов)
  - В блоке лидеров на главной странице можно применять фильтры, которые отобразят - лидеров недели, лидеров месяца, лидеров за все время. В блоке лидеров не отображаются боты
  - Для новых пользователей должно показываться руководство по игре
  - Пользователи-боты должны иметь отличительные знаки от пользователей-людей (иконка бота - у имени пользователя, достижение бота - в профиле пользователя)
  - При создании игры должны быть выставлены настройки по умолчанию
  - Пользователь должен иметь возможность сменить язык программирования в игре
  - В игре в редакторе кода для каждого языка программирования должен отображаться шаблон кода
  - Игры, окончившиеся по истечению времени, не отображаются и не учитываются в статистике
  - Начисление и снятие очков рейтинга должно зависеть от рейтинга оппонентов и от сложности игры
  - На странице настроек профиля должны быть выставлены настройки по умолчанию
  - На странице рейтинга пользователей должно осуществляться постраничное отображение пользователей
  - Пользователь может восстановить пароль от аккаунта 
  - Пользователь может выйти из аккаунта
